from main import *

WINDOW_WIDTH = 600
WINDOW_HEIGHT = 400

WINDOW_CENTRE_X = WINDOW_WIDTH // 2
WINDOW_CENTRE_Y = WINDOW_HEIGHT // 2

PLAYER_ORIGINAL_POS_X = WINDOW_CENTRE_X
PLAYER_ORIGINAL_POS_Y = WINDOW_CENTRE_Y

PLAYER_SPEED_ON_X = 20
PLAYER_SPEED_ON_Y = 20


VERTICAL_VELOCITY = 100
JUMP_STRENGHT = 20

GRAVITY = -1

CIRCLE_RADIUS = 20
CIRCLE_DIAMETER = CIRCLE_RADIUS * 2

